# project-wide basic constants

WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 576
FPS = 60

FOCUS_CAMERA_SCALE = 4 / 3
SMOOTH_SCALE = False

GARBAGE_COLLECTION_INTERVAL_SECONDS = 30
GARBAGE_COLLECTION_INTERVAL_FRAMES = FPS * 30

SAVE_COUNT = 3
