"""constants related to gui"""

import src.constants.base_constants as Constants

TEXT_ANTI_ALIASING = True

DIALOGUE_HEIGHT = 200
DIALOGUE_Y = Constants.WINDOW_HEIGHT - DIALOGUE_HEIGHT
DIALOGUE_BACKGROUND_ALPHA = 128

DIALOGUE_IMAGE_SIZE = 160
DIALOGUE_TEXT_X_NO_IMAGE = 20
DIALOGUE_TEXT_X_WITH_IMAGE = DIALOGUE_TEXT_X_NO_IMAGE * 2 + DIALOGUE_IMAGE_SIZE
DIALOGUE_TEXT_Y = 16
DIALOGUE_TEXT_COLOR = (239, 239, 239)
DIALOGUE_FONT_FILENAME = "fonts/Galmuri14.ttf"
DIALOGUE_GUI_FONT_SIZE = 22

TESTING_GUI_FONT_FILENAME = "fonts/Galmuri14.ttf"
TESTING_GUI_FONT_SIZE = 22

TYPEWRITER_ANIMATION_INDEX_THRESHOLD_NORMAL = int(2 * (Constants.FPS / 60))
TYPEWRITER_ANIMATION_INDEX_THRESHOLD_EXCEPT = int(0.75 * (Constants.FPS / 60))
TYPEWRITER_EXCEPT_CHARS = ' ,/\'\"[]{}()@#$%^&*<>'
