"""constants related to tilemap systems"""

TILE_SIZE = 32
TILEMAP_WIDTH = 32
TILEMAP_HEIGHT = 18
TILEMAP_X_MIN = 1
TILEMAP_Y_MIN = 1
TILEMAP_X_MAX = TILEMAP_WIDTH 
TILEMAP_Y_MAX = TILEMAP_HEIGHT - 1

MOVEMENT_X = [0, -1, 0, 1]
MOVEMENT_Y = [-1, 0, 1, 0]